export const refs = {
  categories: document.querySelector('.categories'),
  products: document.querySelector('.products'),
  searchForm: document.querySelector('.search-form'),
  searchInput: document.querySelector('.search-form__input'),
  clearSearchBtn: document.querySelector('.search-form__btn-clear'),
  loadMoreBtn: document.querySelector('.load-more'),
  notFound: document.querySelector('.not-found'),
  modal: document.querySelector('.modal'),
  modalContent: document.querySelector('.modal-product'),
  closeModalBtn: document.querySelector('.modal__close-btn'),
  wishlistBtn: document.querySelector('.modal-product__wishlist-btn'),
  cartBtn: document.querySelector('.modal-product__cart-btn'),
  buyBtn: document.querySelector('.modal-product__buy-btn'),
  navCounts: document.querySelectorAll('.nav__count'),
  cartSummary: document.querySelector('.cart-summary'),
  cartItems: document.querySelector('.cart-summary__items'),
  cartTotal: document.querySelector('.cart-summary__total'),
  buyProductsBtn: document.querySelector('.cart-summary__buy-btn'),
  loader: document.querySelector('.loader'),
  scrollUpBtn: document.querySelector('.scroll-up'),
  themeToggle: document.querySelector('.theme-toggle'),
};
